apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-target
  namespace: boundary
  labels:
    app: ssh-target
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-target
  template:
    metadata:
      labels:
        app: ssh-target
    spec:
      containers:
        - name: ssh
          image: ssh-target:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 2222
              name: ssh
          volumeMounts:
            - name: vault-ca-key
              mountPath: /etc/ssh/trusted-user-ca-keys.pem
              subPath: trusted-user-ca-keys.pem
      volumes:
        - name: vault-ca-key
          configMap:
            name: ssh-vault-ca
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-target-secret
  namespace: boundary
type: Opaque
stringData:
  # Remplace par un mot de passe sécurisé
  user-password: "xxxxxxxxxxx"
