apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: boundary
type: Opaque
stringData:
  # Remplace par un mot de passe sécurisé — doit correspondre à mysql_root_password dans terraform.tfvars
  root-password: "xxxxxxxxxxx"
