apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: boundary
type: Opaque
stringData:
  # Remplace par des mots de passe sécurisés avant d'appliquer
  root-password: "xxxxxxxxxxxxx"
  boundary-password: "xxxxxxxxxxxxx"
