apiVersion: v1
kind: Service
metadata:
  name: boundary-worker
  namespace: boundary
  labels:
    app: boundary-worker
spec:
  # NodePort pour que le worker soit joignable depuis l'extérieur du cluster
  # (nécessaire pour que les clients Boundary puissent établir des sessions)
  type: NodePort
  selector:
    app: boundary-worker
  ports:
    - name: proxy
      port: 9202
      targetPort: 9202
      nodePort: 30202
      protocol: TCP
