apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: boundary
type: Opaque
stringData:
  root-token: "xxxxxxxxxxxxxx" # Remplace par un token sécurisé — doit correspondre à vault_root_token dans terraform.tfvars
