apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: boundary
  labels:
    app: vault
spec:
  # NodePort so Terraform (running on the host) can reach Vault to configure it
  type: NodePort
  selector:
    app: vault
  ports:
    - name: vault
      port: 8200
      targetPort: 8200
      nodePort: 30200
      protocol: TCP
